# Generated by Django 4.1.2 on 2022-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_blog_description_part2_alter_blog_remember'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blogs/videos'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolios/videos'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='region',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
