# Generated by Django 4.1.2 on 2022-11-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='iframe_src',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='iframe_src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
