# Generated by Django 4.1.2 on 2022-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_blog_iframe_src_portfolio_iframe_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
    ]
